env:
  global:
    - HYPOTHESIS_PROFILE=ci

language: python
matrix:
  include:
    - os: linux
      language: python
      python: '3.5'
    - os: linux
      language: python
      python: '3.6'
    - os: linux
      language: python
      python: '3.7'
      dist: xenial   # required for Python >= 3.7
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2
      language: shell
      python: '3.7'
    - name: "Python 3.7.3 on Windows"
      os: windows
      language: shell
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip3 install -r requirements-test.txt
  - pytest --version

script:
  - pytest
