trigger:
- master
variables:
  HYPOTHESIS_PROFILE: ci

jobs:
- job: 'tests'
  strategy:
    matrix:
      Python35_Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.5'
      Python36_Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.6'
      Python37_Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.7'
      Python38_Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.8'

      Python35_MacOS:
        imageName: 'macos-latest'
        python.version: '3.5'
      Python36_MacOS:
        imageName: 'macos-latest'
        python.version: '3.6'
      Python37_MacOS:
        imageName: 'macos-latest'
        python.version: '3.7'
      Python38_MacOS:
        imageName: 'macos-latest'
        python.version: '3.8'

      Python35_Windows:
        imageName: 'windows-latest'
        python.version: '3.5'
      Python36_Windows:
        imageName: 'windows-latest'
        python.version: '3.6'
      Python37_Windows:
        imageName: 'windows-latest'
        python.version: '3.7'
      Python38_Windows:
        imageName: 'windows-latest'
        python.version: '3.8'

  pool:
    vmImage: '$(imageName)'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'
    - bash: pip install -r requirements-dev.txt
      displayName: Install python packages.
    - bash: pip install -e .
      displayName: Install pyfiledir.
    - bash: echo $OSTYPE; bash --version; python -V; pip --version; pytest --version;
      displayName: Check executables version.
    - bash: pytest
      displayName: Run test.
